% merge multiple hourly .txt files generated by opc_conv.m into one continuous file per TUBSS transect

% TUBSS01
fileID='TUBSS04a.txt'
fopen(fileID)
C = textscan(fileID,'%d %d %d %d', 


%d %{hh:mm:ss}D %d %d %{dd-mmm-yy}D %{hh:mm:ss}D %d %d %f %f %f %f,%f %f %f %f %f %f %f %f %f %f %f %f %f %f %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d','Delimiter',' ');

fclose(fileID)

[R1]=load('R09T04OP.txt')

[T1a]=load('TUBSS01.txt');
[T1b]=load('TUBSS01b.txt');
[T1c]=load('TUBSS01c.txt');
[T1d]=load('TUBSS01d.txt');
[TUBSS01]=cat(1,[T1a;T1b;T1c;T1d]);
save('TUBSS01.mat','TUBSS01')

%TUBSS02
[T2a]=load('TUBSS02a.txt');
[T2b]=load('TUBSS02b.txt');
[T2c]=load('TUBSS02c.txt');
[T2d]=load('TUBSS02d.txt');
[TUBSS02]=cat(1,[T2a;T2b;T2c;T2d]);
save('TUBSS02.mat','TUBSS02')

%TUBSS03
[T3a]=load('TUBSS03a.txt');
[T3b]=load('TUBSS03b.txt');
[T3c]=load('TUBSS03c.txt');
[TUBSS03]=cat(1,[T3a;T3b;T3c]);
save('TUBSS03.mat','TUBSS03')

%TUBSS04
[T4a,b]=load('TUBSS04a.txt');
[T4b]=load('TUBSS04b.txt');
[T4c]=load('TUBSS04c.txt');
[TUBSS04]=cat(1,[T4a;T4b;T4c]);
save('TUBSS04.mat','TUBSS04')

%TUBSS05
[T5a]=load('TUBSS05a.txt');
[T5b]=load('TUBSS05b.txt');
[T5c]=load('TUBSS05c.txt');
[TUBSS05]=cat(1,[T5a;T5b;T5c]);
save('TUBSS05.mat','TUBSS05')

%TUBSS06
[T6a]=load('TUBSS06a.txt');
[T6b]=load('TUBSS06b.txt');
[T6c]=load('TUBSS06c.txt');
[TUBSS06]=cat(1,[T6a;T6b;T6c]);
save('TUBSS06.mat','TUBSS06')


